### PR TITLE
Correct paths to package summary file.

### PR DESCRIPTION
**Pull request by fixermark**

### CODE REVIEW

**Comment by fixermark** [comment]
(Followed procedure for Googlers at https://cla.developers.google.com/clas)

**Comment by sjamesr** [comment]
I think you have to reply "I signed it!" in a comment and then we can merge the change.

Thanks!

**Comment by fixermark** [comment]
i signed it!

**Comment by sjamesr** [comment]
Hmm, googlebot doesn't seem to understand that you've signed the CLA. Can you make sure the commit email and the email you provided to googlebot match?

**Comment by fixermark** [comment]
I think I've got it cleared now.

**Pull request merged**
