### PR TITLE
Replace CASE_RANGES with Character.to{Lower,Upper}Case().

### PR DESCRIPTION
**Pull request by ringw**

### CODE REVIEW

**Comment by alandonovan** [comment]
LGTM

**Comment by ringw** [comment]
The oraclejdk7 and openjdk6 builds are failing with:

```
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE
```

**Comment by sjamesr** [comment]
Looks to be https://github.com/travis-ci/travis-ci/issues/7884, we should just remove oracle jdks from the travis config. Will do that in a few minutes.

**Comment by sjamesr** [comment]
Can you rebase your change? This should fix it: https://github.com/google/re2j/pull/34

**Comment by ringw** [comment]
OpenJDK6 is still failing--maybe they have different UnicodeData? Closing until I investigate further.

**Comment by ringw** [comment]
I'd like to reopen this PR, since it looks like the openjdk6 job that this broke has been removed.

**Comment by ringw** [comment]
Hmm, made a new PR in #78 instead since it's complaining that the branch was force-pushed.

**Pull request closed without merging**
