### PR TITLE
Added new flag Pattern.LONGEST_MATCH ...

### PR DESCRIPTION
**Pull request by mykeul**
... to allow changing hard-coded "longest=false" in Pattern.compile()

### CODE REVIEW

**Comment by sjamesr** [comment]
Thank you, looks good! Do you mind running the code formatter and rebasing your change?

`./gradlew googleJavaFormat` from the project root dir should do the trick

**Comment by mykeul** [comment]
You're welcome. Formatted, rebased, pushed. I'm looking at the CLA.

**Comment by mykeul** [comment]
@googlebot I signed it!

**Comment by sjamesr** [comment]
Thank you!

**Pull request merged**
