### PR TITLE
Tidies up license headers and adds license enforcement.

### PR DESCRIPTION
**Pull request by sjamesr**
This attempts to fix https://github.com/google/re2j/issues/112.

This change attempts to fix up some licensing and copyright
inconsistencies in RE2J. Copyright messages have been amended to specify
"The Go Authors". The BSD-style Go license has been added to the headers
of all Java, Perl and XML source files.

This change utilizes the [License Gradle
Plugin](https://github.com/hierynomus/license-gradle-plugin) in order to
ensure that all source files (java, xml and perl) have an appropriate
LICENSE header.

License violations can be fixed automatically by running
`./gradle licenseFormat`. A message to this effect is displayed if any
license violations are detected.

### CODE REVIEW

**Comment by sjamesr** [comment]
> These new comments practically double the amount of text in the entire repo. It is not necessary.

This contradicts Google's internal requirements, see http://go/releasing/preparing#license-headers: "use the *full text* of that license" (emphasis Google's).

> Please add a short (max 3 line) header that directs to the license file. Take a look at any file in the Go project for example:

Did the Go project get an approval to deviate from the policy? RE2J has none.

**Comment by alandonovan** [comment]
Well, no-one complained so far, either about this project or Go.

**Comment by sjamesr** [comment]
Bytes in repositories are cheap, the policy is clear, but I made the changes as you requested.

**Comment by alandonovan** [comment]
Bytes are cheap, but programmer time is not, and having to scroll down a page literally every single time you open a file is waste of it.

Thanks.

**Pull request merged**
